//
//  Assets.swift
//  Yep
//
//  Created by Octree on 2019/7/4.
//  Copyright © 2019 Octree. All rights reserved.
//

import Foundation

struct Assets {
    var imagesTree: Namespace
    var colorsTree: Namespace
}

func fileComments(title: String, useSwiftUI: Bool = false) -> String {
    let date = Date()
    let formatter = DateFormatter()
    formatter.dateFormat = "yyyy/M/d"
    let dateString = formatter.string(from: date)
    formatter.dateFormat = "yyyy"
    let year = formatter.string(from: date)
    let imports: String
    if useSwiftUI {
        imports = """
        import UIKit
        import SwiftUI
        """
    } else {
        imports = """
        import UIKit
        """
    }
    return """
    //
    //  \(title)
    //
    //  ⚠️ DO NOT EDIT.
    //  Code generated by Yep(https://github.com/octree/Yep) on \(dateString).
    //  Copyright © \(year) Octree. All rights reserved.
    //
    
    \(imports)
    """
}

extension Assets {
    func colorsCode(useSwiftUI: Bool = false) -> String {
        return fileComments(title: "Colors", useSwiftUI: useSwiftUI) + colorsTree.generateCode(useSwiftUI: useSwiftUI)
    }
    
    func imagesCode(useSwiftUI: Bool = false) -> String {
        return fileComments(title: "Images", useSwiftUI: useSwiftUI) + imagesTree.generateCode(useSwiftUI: useSwiftUI)
    }
}
