//
//  Assets.swift
//  Yep
//
//  Created by Octree on 2019/7/4.
//  Copyright © 2019 Octree. All rights reserved.
//

import Foundation

struct Assets {
    var imagesTree: Namespace
    var colorsTree: Namespace
}

func fileComments(title: String, useSwiftUI: Bool = false) -> String {
    let date = Date()
    let formatter = DateFormatter()
    formatter.dateFormat = "yyyy/M/d"
    let dateString = formatter.string(from: date)
    formatter.dateFormat = "yyyy"
    let year = formatter.string(from: date)
    let imports: String
    if useSwiftUI {
        imports = """
        import SwiftUI
        """
    } else {
        imports = """
        import UIKit
        """
    }
    return """
    //
    //  \(title)
    //
    //  ⚠️ DO NOT EDIT.
    //  Code generated by Yep(https://github.com/octree/Yep) on \(dateString).
    //  Copyright © \(year) Octree. All rights reserved.
    //
    
    \(imports)
    
    """
}

extension Assets {
    func colorsCode(useSwiftUI: Bool = false, isSPM: Bool = false) -> String {
        return """
        \(fileComments(title: "Color Assets", useSwiftUI: useSwiftUI))
        extension \(useSwiftUI ? "Color": "UIColor") {
        \(colorsTree.generateCode(indentation: "    ", useSwiftUI: useSwiftUI, isSPM: isSPM, separator: "/"))
        }
        """
    }
    
    func imagesCode(useSwiftUI: Bool = false, isSPM: Bool = true) -> String {
        return """
        \(fileComments(title: "Image Assets", useSwiftUI: useSwiftUI))
        extension \(useSwiftUI ? "Image": "UIImage") {
        \(imagesTree.generateCode(indentation: "    ", useSwiftUI: useSwiftUI, isSPM: isSPM, separator: "/"))
        }
        """
    }
}
